
package sk.kopr.klient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PredmetPort", targetNamespace = "http://localhost:8888/AJS?wsdl")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PredmetPort {


    /**
     * 
     * @param parameters
     * @return
     *     returns sk.kopr.klient.PridajPredmetResponse
     * @throws PredmetExistuje_Exception
     */
    @WebMethod(action = "http://localhost:8888/AJS/pridajPredmet")
    @WebResult(name = "PridajPredmetResponse", targetNamespace = "urn:X-kopr", partName = "parameters")
    public PridajPredmetResponse pridajPredmet(
        @WebParam(name = "PridajPredmetRequest", targetNamespace = "urn:X-kopr", partName = "parameters")
        PridajPredmetRequest parameters)
        throws PredmetExistuje_Exception
    ;

}
